services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME:-nova}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - static_data:/app/static
      - media_data:/app/media
    env_file:
      - .env
    environment:
      DB_ENGINE: postgresql
      DB_HOST: db

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: unless-stopped
    volumes:
      - static_data:/app/static
      - media_data:/app/media
    ports:
      - "80:80" # Change to 443 for HTTPS later
    depends_on:
      - web

volumes:
  postgres_data:
  static_data:
  media_data:
