# Generated by Django 5.2.4 on 2025-07-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='tool_description',
            field=models.TextField(blank=True, help_text='Description of this agent when used as a tool (required if is_tool=True)', null=True),
        ),
    ]
