# Generated by Django 5.2.4 on 2025-07-20 13:11

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0002_agent_tool_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userparameters',
            name='langfuse_host',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userparameters',
            name='langfuse_public_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userparameters',
            name='langfuse_secret_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
