# Generated by Django 5.2.4 on 2025-08-01 16:47

import nova.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0004_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='input_schema',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='output_schema',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
