# Generated by Django 5.2.4 on 2025-08-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0005_alter_tool_input_schema_alter_tool_output_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('streamable_http', 'Streamable HTTP (Default)'), ('sse', 'SSE (Legacy)')], default='streamable_http', help_text='Transport method for MCP servers', max_length=20),
        ),
    ]
