# Generated by Django 5.2.5 on 2025-08-13 11:57

import nova.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0006_add_transport_type_to_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userparameters',
            name='langfuse_host',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[nova.models.validate_relaxed_url]),
        ),
    ]
