# Generated by Django 5.2.5 on 2025-08-19 18:34

import django.db.models.deletion
import nova.models.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0006_add_transport_type_to_tool'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='max_context_tokens',
            field=models.PositiveIntegerField(default=4096, help_text="Maximum tokens for this provider's context window (e.g., 4096 for small models, 100000 or more for large)."),
        ),
        migrations.AddField(
            model_name='message',
            name='internal_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='tool',
            name='input_schema',
            field=models.JSONField(blank=True, default=nova.models.Tool.get_default_schema, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='output_schema',
            field=models.JSONField(blank=True, default=nova.models.Tool.get_default_schema, null=True),
        ),
        migrations.AlterField(
            model_name='userparameters',
            name='langfuse_host',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[nova.models.models.validate_relaxed_url]),
        ),
        migrations.CreateModel(
            name='CheckpointLink',
            fields=[
                ('checkpoint_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nova.agent')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint_links', to='nova.thread')),
            ],
            options={
                'unique_together': {('thread', 'agent')},
            },
        ),
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='nova.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'key')},
            },
        ),
    ]
