# Generated by Django 5.2.5 on 2025-08-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0007_llmprovider_max_context_tokens_message_internal_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='recursion_limit',
            field=models.IntegerField(default=25),
        ),
    ]
