# Generated by Django 5.2.5 on 2025-08-25 07:49

import nova.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0008_agent_recursion_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmprovider',
            name='base_url',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[nova.models.models.validate_relaxed_url]),
        ),
    ]
