# Generated by Django 5.2.5 on 2025-08-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0008_userfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
