# Generated by Django 5.2.5 on 2025-08-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0009_alter_userfile_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='internal_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
