# Generated by Django 5.2.5 on 2025-08-27 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0010_alter_llmprovider_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_tools',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_tool': True}, related_name='used_by_agents', to='nova.agent', verbose_name='Agents to use as tools'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='is_tool',
            field=models.BooleanField(default=False, help_text='If true, this agent can be used as a tool by other agents.', verbose_name='Is tool'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='llm_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='nova.llmprovider', verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='recursion_limit',
            field=models.IntegerField(default=25, verbose_name='Recursion limit'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='system_prompt',
            field=models.TextField(verbose_name='Prompt'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='tool_description',
            field=models.TextField(blank=True, help_text='Description of this agent when used as a tool (required if is_tool=True)', null=True, verbose_name='Tool description'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='agents', to='nova.tool', verbose_name='Tools'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='max_context_tokens',
            field=models.PositiveIntegerField(default=4096, help_text="Maximum tokens for this provider's context window\n                       (e.g., 4096 for small models, 100000 or more for large)."),
        ),
    ]
