# Generated by Django 5.2.5 on 2025-08-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0010_message_internal_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='max_context_tokens',
            field=models.PositiveIntegerField(default=4096, help_text="Maximum tokens for this provider's context window (e.g., 4096 for small models, 100000 or more for large)."),
        ),
    ]
