# Generated by Django 5.2.5 on 2025-08-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0011_alter_agent_agent_tools_alter_agent_is_tool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userparameters',
            name='has_api_token',
            field=models.BooleanField(default=False, help_text='Whether user has generated an API token'),
        ),
    ]
