# Generated by Django 5.2.5 on 2025-08-28 14:12

import nova.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0012_userparameters_has_api_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='endpoint',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[nova.models.models.validate_relaxed_url]),
        ),
    ]
