# Generated by Django 5.2.6 on 2025-10-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0016_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='actor',
            field=models.CharField(choices=[('USR', 'User'), ('AGT', 'Agent'), ('SYS', 'System')], max_length=3),
        ),
    ]
