# Generated by Django 5.2.7 on 2025-10-27 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0017_alter_message_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('AWAITING_INPUT', 'Awaiting user input'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Origin (display name)')),
                ('question', models.TextField(verbose_name='Question to user')),
                ('schema', models.JSONField(blank=True, default=dict, null=True)),
                ('resume_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ANSWERED', 'Answered'), ('CANCELED', 'Canceled')], default='PENDING', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='nova.agent', verbose_name='Agent')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='nova.task', verbose_name='Task')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='nova.thread', verbose_name='Thread')),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
                'indexes': [models.Index(fields=['task', 'status'], name='nova_intera_task_id_61e122_idx'), models.Index(fields=['thread', 'status'], name='nova_intera_thread__7870eb_idx'), models.Index(fields=['created_at'], name='nova_intera_created_0b035a_idx')],
            },
        ),
    ]
