# Generated by Django 5.2.7 on 2025-10-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0018_alter_task_status_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='answer',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='User answer'),
        ),
    ]
