# Generated by Django 5.2.7 on 2025-10-27 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0019_interaction_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='interaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='messages', to='nova.interaction', verbose_name='Related interaction'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('standard', 'Standard message'), ('interaction_question',
                                                                               'Agent question to user'),
                                            ('interaction_answer', 'User answer to agent question')],
                                   default='standard', max_length=20, verbose_name='Message type'),
        ),
    ]
