# Generated by Django 5.2.7 on 2025-10-28 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0020_add_interaction_message_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('system_prompt', models.TextField(verbose_name='Prompt')),
                ('recursion_limit', models.IntegerField(default=25, verbose_name='Recursion limit')),
                ('is_tool', models.BooleanField(default=False, help_text='If true, this agent can be used as a tool by other agents.', verbose_name='Is tool')),
                ('tool_description', models.TextField(blank=True, help_text='Description of this agent when used as a tool (required if is_tool=True)', null=True, verbose_name='Tool description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_tools', models.ManyToManyField(blank=True, limit_choices_to={'is_tool': True}, related_name='used_by_agents', to='nova.agentconfig', verbose_name='Agents to use as tools')),
                ('llm_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AgentsConfig', to='nova.llmprovider', verbose_name='Provider')),
                ('tools', models.ManyToManyField(blank=True, related_name='agents', to='nova.tool', verbose_name='Tools')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_agents', to=settings.AUTH_USER_MODEL, verbose_name='User agents')),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='checkpointlink',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nova.agentconfig'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='nova.agentconfig', verbose_name='AgentConfig'),
        ),
        migrations.AlterField(
            model_name='task',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='nova.agentconfig', verbose_name='AgentConfig'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nova.agentconfig'),
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
