# Generated by Django 5.2.7 on 2025-10-29 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0021_agentconfig_alter_checkpointlink_agent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='agent',
        ),
        migrations.AddField(
            model_name='interaction',
            name='agent_config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='nova.agentconfig', verbose_name='AgentConfig'),
            preserve_default=False,
        ),
    ]
