# Generated by Django 5.2.8 on 2025-11-10 14:34

import django.db.models.deletion
import nova.models.WebApp
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0022_remove_interaction_agent_interaction_agent_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmprovider',
            name='provider_type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('mistral', 'Mistral'), ('ollama', 'Ollama'), ('llama.cpp', 'llama.cpp'), ('lmstudio', 'LMStudio')], default='ollama', max_length=32),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='markdown_content',
            field=models.TextField(blank=True, default='# global_user_preferences\n', help_text='User information stored in Markdown format', max_length=50000),
        ),
        migrations.CreateModel(
            name='WebApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=nova.models.WebApp.uuid_hex, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webapps', to='nova.thread', verbose_name='Thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webapps', to=settings.AUTH_USER_MODEL, verbose_name='User webapps')),
            ],
            options={
                'verbose_name': 'Web application',
                'verbose_name_plural': 'Web applications',
                'indexes': [models.Index(fields=['slug'], name='nova_webapp_slug_d639b7_idx'), models.Index(fields=['user'], name='nova_webapp_user_id_4a4d5b_idx'), models.Index(fields=['thread'], name='nova_webapp_thread__d6dc19_idx')],
            },
        ),
    ]
