# Generated by Django 5.2.8 on 2025-11-10 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0023_alter_llmprovider_provider_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAppFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='Example: index.html, styles.css, app.js', max_length=120, verbose_name='Path (filename)')),
                ('content', models.TextField(help_text='File content (UTF-8). Max 200 KB per file.', verbose_name='Content')),
                ('webapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='nova.webapp', verbose_name='Web application')),
            ],
            options={
                'verbose_name': 'Web application file',
                'verbose_name_plural': 'Web application files',
                'indexes': [models.Index(fields=['webapp', 'path'], name='nova_webapp_webapp__79df61_idx')],
                'unique_together': {('webapp', 'path')},
            },
        ),
    ]
