# Generated by Django 5.2.8 on 2025-11-30 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0024_webappfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Task name')),
                ('prompt', models.TextField(verbose_name='Prompt')),
                ('cron_expression', models.CharField(max_length=100, verbose_name='Cron expression')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='Timezone')),
                ('keep_thread', models.BooleanField(default=True, verbose_name='Keep thread after execution')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='Last error')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Last run at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='nova.agentconfig', verbose_name='Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Scheduled task',
                'verbose_name_plural': 'Scheduled tasks',
                'unique_together': {('user', 'name')},
            },
        ),
    ]
