# Generated by Django 5.2.8 on 2025-11-30 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0025_scheduledtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='agent',
            new_name='agent_config',
        ),
    ]
