# Generated by Django 5.2.9 on 2025-12-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0026_rename_agent_task_agent_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='current_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
