# Generated by Django 5.2.9 on 2025-12-30 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0027_add_current_response_to_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummarizationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_summarize', models.BooleanField(default=True, help_text='Enable automatic conversation summarization', verbose_name='Auto-summarize')),
                ('token_threshold', models.IntegerField(default=3000, help_text='Trigger summarization when context exceeds this token count', verbose_name='Token threshold')),
                ('summary_model', models.CharField(blank=True, help_text='Optional model override for summarization (leave blank to use agent model)', max_length=100, verbose_name='Summary model')),
                ('preserve_recent', models.IntegerField(default=5, help_text='Number of recent messages to keep unsummarized', verbose_name='Preserve recent messages')),
                ('strategy', models.CharField(choices=[('conversation', 'Conversation Summary'), ('topic', 'Topic-based Summary'), ('temporal', 'Temporal Summary'), ('hybrid', 'Hybrid Summary')], default='conversation', help_text='Strategy for summarizing conversations', max_length=50, verbose_name='Summarization strategy')),
                ('max_summary_length', models.IntegerField(default=1000, help_text='Maximum length of summary in words', verbose_name='Max summary length')),
                ('compression_ratio', models.FloatField(default=0.3, help_text='Target size reduction (0.3 = 30% of original)', verbose_name='Compression ratio')),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summarization_config', to='nova.agentconfig', verbose_name='Agent')),
            ],
            options={
                'verbose_name': 'Summarization Configuration',
                'verbose_name_plural': 'Summarization Configurations',
            },
        ),
    ]
