# Generated by Django 5.2.9 on 2025-12-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0028_summarizationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfig',
            name='auto_summarize',
            field=models.BooleanField(default=False, help_text='Enable automatic summarization when token threshold is reached'),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='max_summary_length',
            field=models.IntegerField(default=500, help_text='Maximum length of generated summary in words'),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='preserve_recent',
            field=models.IntegerField(default=2, help_text='Number of recent messages to preserve'),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='strategy',
            field=models.CharField(default='conversation', help_text='Summarization strategy: conversation, topic, temporal, hybrid', max_length=20),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='summary_model',
            field=models.CharField(blank=True, help_text='Optional LLM model override for summarization', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='token_threshold',
            field=models.IntegerField(default=100, help_text='Token count threshold for triggering summarization'),
        ),
        migrations.DeleteModel(
            name='SummarizationConfig',
        ),
    ]
