# Generated by Django 5.2.9 on 2026-01-30

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0030_memory_models_pgvector'),
    ]

    operations = [
        migrations.AddField(
            model_name='userparameters',
            name='memory_embeddings_enabled',
            field=models.BooleanField(default=False, help_text='Enable semantic (embedding) search for long-term memory'),
        ),
        migrations.AddField(
            model_name='userparameters',
            name='memory_embeddings_url',
            field=models.CharField(blank=True, default='', help_text='Embeddings endpoint URL (OpenAI-compatible /v1 recommended)', max_length=400),
        ),
        migrations.AddField(
            model_name='userparameters',
            name='memory_embeddings_model',
            field=models.CharField(blank=True, default='', help_text='Embeddings model name', max_length=200),
        ),
        migrations.AddField(
            model_name='userparameters',
            name='memory_embeddings_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='API key for the embeddings endpoint (optional)', max_length=255, null=True),
        ),
    ]
