# Generated by Django 5.2.9 on 2026-01-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0034_simplify_memory_item_lifecycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentconfig',
            name='token_threshold',
            field=models.IntegerField(default=10000, help_text='Token count threshold for triggering summarization'),
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
