# Generated by Django 5.2.9 on 2026-02-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0035_alter_agentconfig_token_threshold_delete_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='mode',
            field=models.CharField(choices=[('thread', 'Thread'), ('continuous', 'Continuous')], db_index=True, default='thread', help_text='Conversation mode: standard thread or continuous discussion', max_length=16),
        ),
    ]
