# Generated by Django 5.2.9 on 2026-02-01 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0036_thread_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DaySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_label', models.DateField(db_index=True)),
                ('summary_markdown', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_segment_starts', to='nova.message', verbose_name='Starts at message')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_segments', to='nova.thread', verbose_name='Thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_segments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'thread', 'day_label'], name='nova_dayseg_user_id_697f5a_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'thread', 'day_label'), name='uniq_daysegment_user_thread_day')],
            },
        ),
    ]
