# Generated by Django 5.2.9 on 2026-02-01 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0037_continuous_daysegment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_text', models.TextField(help_text='Normalized concatenation of message contents')),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('token_estimate', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcript_chunks', to='nova.daysegment', verbose_name='Day segment')),
                ('end_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transcript_chunk_ends', to='nova.message', verbose_name='End message')),
                ('start_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transcript_chunk_starts', to='nova.message', verbose_name='Start message')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_chunks', to='nova.thread', verbose_name='Thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_chunks', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'thread', 'day_segment', 'start_message'], name='idx_chunk_day_start'), models.Index(fields=['user', 'thread', 'end_message'], name='idx_chunk_end')],
                'constraints': [models.UniqueConstraint(fields=('user', 'thread', 'start_message', 'end_message'), name='uniq_chunk_user_thread_bounds')],
            },
        ),
    ]
