# Generated by Django 5.2.9 on 2026-02-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0038_continuous_transcriptchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointlink',
            name='continuous_context_built_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkpointlink',
            name='continuous_context_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
