# Generated by Django 5.2.9 on 2026-02-01 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0039_continuous_checkpointlink_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='daysegment',
            name='summary_until_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='day_segment_summary_until', to='nova.message', verbose_name='Summary until message'),
        ),
    ]
