# Generated by Django 5.2.7 on 2026-02-01 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nova", "0040_continuous_daysegment_summary_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledtask",
            name="task_kind",
            field=models.CharField(
                choices=[("agent", "Agent"), ("maintenance", "Maintenance")],
                default="agent",
                max_length=32,
                verbose_name="Task kind",
            ),
        ),
        migrations.AddField(
            model_name="scheduledtask",
            name="maintenance_task",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Celery task name, e.g. 'continuous_nightly_daysegment_summaries_for_user'.",
                max_length=255,
                verbose_name="Maintenance task",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledtask",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduled_tasks",
                to="nova.agentconfig",
                verbose_name="Agent",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledtask",
            name="prompt",
            field=models.TextField(blank=True, default="", verbose_name="Prompt"),
        ),
    ]

