# Generated by Django 5.2.9 on 2026-02-07 17:42

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


def create_conversation_vector_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        "CREATE INDEX IF NOT EXISTS idx_daysegment_embedding_vector_hnsw "
        "ON nova_daysegmentembedding USING hnsw (vector vector_cosine_ops);"
    )
    schema_editor.execute(
        "CREATE INDEX IF NOT EXISTS idx_transcriptchunk_embedding_vector_hnsw "
        "ON nova_transcriptchunkembedding USING hnsw (vector vector_cosine_ops);"
    )


def drop_conversation_vector_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute("DROP INDEX IF EXISTS idx_daysegment_embedding_vector_hnsw;")
    schema_editor.execute("DROP INDEX IF EXISTS idx_transcriptchunk_embedding_vector_hnsw;")


class Migration(migrations.Migration):

    dependencies = [
        ("nova", "0042_remove_system_periodic_task_continuous_nightly"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DaySegmentEmbedding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider_type", models.CharField(blank=True, default="", max_length=40)),
                ("model", models.CharField(blank=True, default="", max_length=120)),
                ("dimensions", models.IntegerField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("pending", "pending"), ("ready", "ready"), ("error", "error")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("vector", pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day_segment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="nova.daysegment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_segment_embeddings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["user", "state"], name="idx_dayseg_embed_u_state")],
            },
        ),
        migrations.CreateModel(
            name="TranscriptChunkEmbedding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider_type", models.CharField(blank=True, default="", max_length=40)),
                ("model", models.CharField(blank=True, default="", max_length=120)),
                ("dimensions", models.IntegerField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("pending", "pending"), ("ready", "ready"), ("error", "error")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("vector", pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transcript_chunk",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="nova.transcriptchunk",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript_chunk_embeddings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["user", "state"], name="idx_chunk_embed_u_state")],
            },
        ),
        migrations.RunPython(create_conversation_vector_indexes, reverse_code=drop_conversation_vector_indexes),
    ]
