# Generated by Django 5.2.8 on 2026-02-08 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def cleanup_legacy_scheduled_periodic_tasks(apps, schema_editor):
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    PeriodicTask.objects.filter(name__startswith="scheduled_task_").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("nova", "0043_conversation_embeddings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_celery_beat", "0018_improve_crontab_helptext"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, verbose_name="Task name")),
                (
                    "task_kind",
                    models.CharField(
                        choices=[("agent", "Agent"), ("maintenance", "Maintenance")],
                        default="agent",
                        max_length=32,
                        verbose_name="Task kind",
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[("cron", "Schedule (cron)"), ("email_poll", "Email polling")],
                        default="cron",
                        max_length=32,
                        verbose_name="Trigger type",
                    ),
                ),
                ("prompt", models.TextField(blank=True, default="", verbose_name="Prompt")),
                (
                    "run_mode",
                    models.CharField(
                        choices=[
                            ("new_thread", "New thread"),
                            ("continuous_message", "Message in Continuous"),
                            ("ephemeral", "Ephemeral (no persisted thread)"),
                        ],
                        default="new_thread",
                        max_length=32,
                        verbose_name="Run mode",
                    ),
                ),
                ("cron_expression", models.CharField(blank=True, default="", max_length=100, verbose_name="Cron expression")),
                ("timezone", models.CharField(default="UTC", max_length=50, verbose_name="Timezone")),
                (
                    "poll_interval_minutes",
                    models.PositiveSmallIntegerField(default=5, verbose_name="Polling interval (minutes)"),
                ),
                (
                    "maintenance_task",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Celery task name, e.g. 'continuous_nightly_daysegment_summaries_for_user'.",
                        max_length=255,
                        verbose_name="Maintenance task",
                    ),
                ),
                ("runtime_state", models.JSONField(blank=True, default=dict, verbose_name="Runtime state")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active")),
                ("last_error", models.TextField(blank=True, null=True, verbose_name="Last error")),
                ("last_run_at", models.DateTimeField(blank=True, null=True, verbose_name="Last run at")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_definitions",
                        to="nova.agentconfig",
                        verbose_name="Agent",
                    ),
                ),
                (
                    "email_tool",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_definitions",
                        to="nova.tool",
                        verbose_name="Email tool",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_definitions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task definition",
                "verbose_name_plural": "Task definitions",
                "unique_together": {("user", "name")},
            },
        ),
        migrations.DeleteModel(
            name="ScheduledTask",
        ),
        migrations.RunPython(cleanup_legacy_scheduled_periodic_tasks, migrations.RunPython.noop),
    ]
