# Generated by Django 5.2.11 on 2026-02-10 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0044_taskdefinition_remove_scheduledtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='userparameters',
            name='continuous_default_messages_limit',
            field=models.PositiveIntegerField(default=40, help_text='Number of recent messages shown in Continuous mode when no day is selected.', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
