# Generated by Django 5.2.11 on 2026-02-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nova", "0047_remove_interaction_resume_payload"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userparameters",
            name="task_notifications_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable browser push notifications when background tasks complete or fail.",
            ),
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("endpoint", models.TextField(unique=True)),
                ("p256dh", models.TextField()),
                ("auth", models.TextField()),
                ("expiration_time", models.DateTimeField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, default="", max_length=512)),
                ("is_active", models.BooleanField(default=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User push subscriptions",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "is_active"], name="nova_pushsu_user_id_520295_idx"),
                    models.Index(fields=["updated_at"], name="nova_pushsu_updated_1d4d3b_idx"),
                ],
            },
        ),
    ]
