# Generated by Django 5.2.8 on 2026-03-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nova", "0048_pushsubscription_userparameters_task_notifications_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="webapp",
            name="name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]

