# Generated by Django 5.2.5 on 2026-03-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nova", "0049_webapp_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="streamed_markdown",
            field=models.TextField(blank=True, default=""),
        ),
    ]

