# Generated by Django 5.2.8 on 2026-03-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nova", "0050_task_streamed_markdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfile",
            name="scope",
            field=models.CharField(
                choices=[
                    ("thread_shared", "Thread shared"),
                    ("message_attachment", "Message attachment"),
                ],
                db_index=True,
                default="thread_shared",
                max_length=32,
            ),
        ),
    ]
