# Generated by Django 6.0.3 on 2026-03-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0052_userfile_source_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='validated_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='validation_capabilities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='validation_status',
            field=models.CharField(choices=[('untested', 'Untested'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('stale', 'Stale')], db_index=True, default='untested', max_length=16),
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='validation_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
