# Generated by Django 6.0.3 on 2026-03-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nova", "0053_llmprovider_validation"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmprovider",
            name="validation_requested_fingerprint",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="llmprovider",
            name="validation_task_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="llmprovider",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("untested", "Untested"),
                    ("testing", "Testing"),
                    ("valid", "Valid"),
                    ("invalid", "Invalid"),
                    ("stale", "Stale"),
                ],
                db_index=True,
                default="untested",
                max_length=16,
            ),
        ),
    ]
