# Generated by Django 6.0.3 on 2026-03-08 15:30

from urllib.parse import urlsplit

from django.db import migrations, models


OPENROUTER_ALLOWED_PATHS = {"", "/", "/api", "/api/", "/api/v1", "/api/v1/"}


def _is_openrouter_base_url(base_url: str | None) -> bool:
    if not base_url:
        return False

    parsed = urlsplit(base_url.strip())
    hostname = (parsed.hostname or "").lower()
    path = parsed.path or ""
    normalized_path = f"{path.rstrip('/')}/" if path.rstrip("/") in {"/api", "/api/v1"} else (path or "/")
    return hostname == "openrouter.ai" and normalized_path in OPENROUTER_ALLOWED_PATHS


def migrate_openai_openrouter_providers(apps, schema_editor):
    LLMProvider = apps.get_model("nova", "LLMProvider")

    for provider in LLMProvider.objects.filter(provider_type="openai").iterator():
        if _is_openrouter_base_url(provider.base_url):
            provider.provider_type = "openrouter"
            provider.save(update_fields=["provider_type"])


class Migration(migrations.Migration):

    dependencies = [
        ("nova", "0054_llmprovider_validation_task_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmprovider",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("openrouter", "OpenRouter"),
                    ("mistral", "Mistral"),
                    ("ollama", "Ollama"),
                    ("llama.cpp", "llama.cpp"),
                    ("lmstudio", "LMStudio"),
                ],
                default="ollama",
                max_length=32,
            ),
        ),
        migrations.RunPython(
            migrate_openai_openrouter_providers,
            migrations.RunPython.noop,
        ),
    ]
