# Generated by Django 5.2.11 on 2026-03-31

from django.db import migrations, models


def forwards_memory_embeddings_source(apps, schema_editor):
    UserParameters = apps.get_model("nova", "UserParameters")

    for params in UserParameters.objects.all().iterator():
        if bool(getattr(params, "memory_embeddings_enabled", False)) and (params.memory_embeddings_url or "").strip():
            params.memory_embeddings_source = "custom"
        else:
            params.memory_embeddings_source = "system"
        params.save(update_fields=["memory_embeddings_source"])


def backwards_memory_embeddings_source(apps, schema_editor):
    UserParameters = apps.get_model("nova", "UserParameters")

    for params in UserParameters.objects.all().iterator():
        params.memory_embeddings_enabled = bool(
            params.memory_embeddings_source == "custom" and (params.memory_embeddings_url or "").strip()
        )
        params.save(update_fields=["memory_embeddings_enabled"])


class Migration(migrations.Migration):

    dependencies = [
        ("nova", "0062_task_execution_trace"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmbeddingsSystemState",
            fields=[
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(
                        default=1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider_available", models.BooleanField(default=False)),
                ("current_fingerprint", models.CharField(blank=True, default="", max_length=64)),
                ("last_backfill_provider_available", models.BooleanField(default=False)),
                ("last_backfill_fingerprint", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="userparameters",
            name="memory_embeddings_source",
            field=models.CharField(
                choices=[
                    ("system", "System provider"),
                    ("custom", "Custom provider"),
                    ("disabled", "Disabled"),
                ],
                default="system",
                help_text="Select which embeddings provider source should be used for semantic search",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            forwards_memory_embeddings_source,
            backwards_memory_embeddings_source,
        ),
        migrations.RemoveField(
            model_name="userparameters",
            name="memory_embeddings_enabled",
        ),
    ]
