# Generated by Django 6.0.7 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nova", "0083_remove_agentconfig_legacy_summarization_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="archived_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
