services:
  web:
    extends:
      file: docker-compose.base.yml
      service: web
    environment:
      - SEARNGX_SERVER_URL=http://searxng:8080

  searxng:
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    volumes:
      - ./searxng:/etc/searxng:rw
      - searxng-data:/var/cache/searxng:rw
    environment:
      - SEARXNG_PORT=8080
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

volumes:
  searxng-data:
