services:
  web:
    extends:
      file: docker-compose.base.yml
      service: web
    environment:
      - OLLAMA_SERVER_URL=http://ollama:11434
      - OLLAMA_MODEL_NAME=${OLLAMA_MODEL_NAME:-NovaModel}
      - OLLAMA_CONTEXT_LENGTH=${OLLAMA_CONTEXT_LENGTH:-4096}

  ollama:
    image: ollama/ollama:latest
    environment:
      - OLLAMA_KEEP_ALIVE="24h"
      - OLLAMA_MODEL_NAME=${OLLAMA_MODEL_NAME:-NovaModel}
      - OLLAMA_CONTEXT_LENGTH=${OLLAMA_CONTEXT_LENGTH:-4096}
    volumes:
      - ./ollama/modelfiles:/modelfiles:ro
      - ./ollama/ollama_entrypoint.sh:/ollama_entrypoint.sh
      - ollama_storage:/root/.ollama
    entrypoint: ["./ollama_entrypoint.sh"]
    restart: unless-stopped

volumes:
  ollama_storage:
